### PR TITLE
Adds link to jonathanio/update-systemd-resolved

### PR DESCRIPTION
**Pull request by piotr-dobrogost**
Adds information about https://github.com/jonathanio/update-systemd-resolved project.
Fixes issue #13

### CODE REVIEW

**Comment by masterkorp** [comment]
Thank you for help.

I'd prefer for such information to be on the README, to avoid script bloat.

**Comment by piotr-dobrogost** [comment]
You mean this file nobody reads? :)
Ok, will do.

**Comment by masterkorp** [comment]
Ping, any news?

**Comment by piotr-dobrogost** [comment]
Thank you for reminding me.
Now information is in README instead.

**Comment by masterkorp** [comment]
Thank you, merged.

**Pull request merged**
